FROM node:19-alpine3.17

WORKDIR /app

ADD package.json package-lock.json tsconfig.json ./

RUN addgroup -S nonroot \
    && adduser -S nonroot -G nonroot
    
USER nonroot

RUN npm install

EXPOSE 3000

ADD ./src ./src

CMD ["npm","run","dev"]