#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

protected_branches=('main' 'develop')

current_branch=$(git rev-parse --abbrev-ref HEAD)

print_policy(){
    echo -e "\n\n[Policy] Never push code directly to the "$1" branch! (Prevented with pre-push hook.)\n\n"
}  

do_exit(){
  print_policy $1
  exit 1
}

for protected_branch in ${protected_branches[@]}; do
    if [ $current_branch = $protected_branch ]; then
        do_exit $protected_branch
    fi
done

unset do_exit

exit 0